version: '3'

services:
  jenkins:
    build:
      context: .
    restart: always
    ports:
      - 8088:8080
      - 50000:50000
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.euzeo.be`)"