version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    depends_on: 
      - 'reverse-proxy'
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.euzeo.be'
        # Add any other gitlab.rb configuration here, each on its own line
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`gitlab.euzeo.be`)"
    ports:
      - '88:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

  jenkins:
    build:
      context: .
    restart: always
    ports:
      - 8088:8080
      - 50000:50000
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.euzeo.be`)"
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'